# Generated by Django 5.0.1 on 2024-04-19 06:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('web_name', models.CharField(blank=True, max_length=100)),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('second_name', models.CharField(blank=True, max_length=100)),
                ('team', models.IntegerField(default=0)),
                ('element_type', models.IntegerField(default=0)),
                ('minutes', models.IntegerField(default=0)),
                ('goals_scored', models.IntegerField(default=0)),
                ('assists', models.IntegerField(default=0)),
                ('clean_sheets', models.IntegerField(default=0)),
                ('saves', models.IntegerField(default=0)),
                ('photo', models.ImageField(blank=True, upload_to='')),
                ('position', models.CharField(blank=True, max_length=200)),
                ('team_name', models.CharField(blank=True, max_length=200)),
                ('influence', models.DecimalField(decimal_places=3, default=0.0, max_digits=7)),
                ('total_points', models.IntegerField(default=0)),
                ('selected_by_percent', models.CharField(blank=True, max_length=200)),
                ('value_form', models.CharField(blank=True, max_length=200)),
                ('value_season', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerInTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_captain', models.BooleanField(default=False)),
                ('is_vice_captain', models.BooleanField(default=False)),
                ('total_points', models.IntegerField(default=0)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.player')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('budget', models.DecimalField(decimal_places=2, default=100.0, max_digits=10)),
                ('total_points', models.IntegerField(default=0)),
                ('players', models.ManyToManyField(related_name='teams', through='app1.PlayerInTeam', to='app1.player')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='playerinteam',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.team'),
        ),
    ]
