# Generated by Django 5.0.1 on 2024-04-22 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_alter_player_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='photo',
            field=models.URLField(blank=True, null=True),
        ),
    ]
